---
- name: 'Update/Upgrade apt packages'
  become: yes
  apt:
    force_apt_get: yes
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400

- name: 'Install packages'
  become: yes
  apt:
    force_apt_get: yes
    pkg:
    - git
    - iperf3
    - screen
    - sysbench