---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openfaas-figlet
  labels:
   app: openfaas-figlet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openfaas-figlet
  template:
    metadata:
      labels:
        app: openfaas-figlet
    spec:
      containers:
      - name: openfaas-figlet
        image: functions/figlet:latest-armhf
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
      tolerations:
      - key: "key"
        operator: "Exists"
        effect: "NoSchedule"



---
apiVersion: v1
kind: Service
metadata:
  name: openfaas-figlet
  labels:
    app: openfaas-figlet
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: http
  selector:
    app: openfaas-figlet



---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: openfaas-figlet
spec:
  backend:
    serviceName: openfaas-figlet
    servicePort: 8080
