---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openfaas-figlet
  labels:
   app: openfaas-figlet
spec:
  replicas: 2
  selector:
    matchLabels:
      app: openfaas-figlet
  template:
    metadata:
      labels:
        app: openfaas-figlet
    spec:
      containers:
      - name: figlet
        image: functions/figlet:latest-armhf
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: openfaas-figlet-svc
spec:
  selector:
    app: openfaas-figlet
  ports:
    - port: 8080
      protocol: TCP
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: openfaas-figlet-ingress
  annotations:
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - http:
      paths:
      - path: /figlet
        backend:
          serviceName: openfaas-figlet-svc
          servicePort: 8080
