---
- hosts: bramble
  user: pi
  roles:
    - { role: 'common', tags: 'common' }
    - { role: 'node_exporter', tags: 'node_exporter' }
    - { role: 'rpi_exporter', tags: 'rpi_exporter' }

- hosts: bramble-s
  user: pi
  roles:
    - { role: 'k3s-agent', tags: 'k3s-agent' }

- hosts: bramble-m
  user: pi
  roles:
    - { role: 'prometheus', tags: 'prometheus' }
    - { role: 'grafana', tags: 'grafana' }
    - { role: 'k3s', tags: 'k3s' }
    - { role: 'nfs', tags: 'nfs' }